name: erobot_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.3.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/image.png
    - assets/images/channel.png
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Italic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Light.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-LightItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBoldItalic.ttf
