name: erobot_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  japx: 2.0.3
  get_storage: 2.0.3
  json_annotation: ^4.4.0
  adaptive_dialog: ^1.4.0
  http_interceptor: 1.0.2
  getwidget: ^2.0.5
  flutter_bluetooth_serial: 0.4.0
  flutter_swipe_action_cell: ^2.2.0
  flutter_countdown_timer: 4.1.0
  fluttertoast: ^8.0.9
  url_launcher: ^6.0.20
  font_awesome_flutter: ^10.1.0
  sleek_circular_slider: 2.0.1
  flutter_staggered_grid_view: ^0.6.1
  decorated_icon: 1.2.1
  flutter:
    sdk: flutter
  page_indicator: ^0.4.1
  photo_view: ^0.13.0
  flutter_markdown: ^0.6.9
  logger: ^1.1.0
  intl: ^0.17.0
  share_plus: ^4.0.1
  lazy_load_scrollview: ^1.3.0
  flutter_pagewise: ^2.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Italic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Light.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-LightItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBoldItalic.ttf
  uses-material-design: true
