name: Central Market

on: [pull_request]
jobs:
  execute:
    name: Code Quality
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flutter_version: [3.7.0]
        flutter_path: ["/opt/hostedtoolcache/flutter"]

    steps:
      - uses: actions/checkout@v3

      - name: Create .api_constant.dart file
        run: cat lib/constants/api_constant.dart.example > lib/constants/api_constant.dart

      - name: Load Flutter SDK from Cache
        uses: actions/cache@v3.2.6
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter-${{ matrix.flutter_version }}

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ matrix.flutter_version }}

      - name: Install Packages
        run: flutter pub get

      - name: Execute Build Runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Check Code Formats
        run: dart format $(find lib -name "*.dart" -not \( -name "*.g.dart" -o -name "*.gr.dart" \)) --set-exit-if-changed --line-length 120

      - name: Check Linters
        run: flutter analyze

      - name: Execute Tests
        run: flutter test
